id = "swift"
name = "Swift"
description = "Swift support."
version = "0.2.0"
schema_version = 1
authors = ["ejjonny <https://github.com/ejjonny>", "Samuser107 L.Longheval <samuser107@gmail.com>"]
repository = "https://github.com/zed-industries/zed"

[language_servers.sourcekit-lsp]
name = "sourcekit-lsp"
language = "Swift"

[grammars.swift]
repository = "https://github.com/alex-pinkus/tree-sitter-swift"
commit = "caa99d7d3c14aac03b5f16fc86fedf8755570760"
